#!/bin/bash
if [ -d /etc/ppp/ip-up.d -a -d /etc/ppp/ip-down.d ]
then
	# SUSE mode
	rm -f /etc/ppp/ip-up.d/sslvpnroute*
	rm -f /etc/ppp/ip-down.d/sslvpnroute*
	rm -f /etc/ppp/ipv6-up.d/sslvpnroute*
	rm -f /etc/ppp/ipv6-down.d/sslvpnroute*
else
	# Non-SUSE mode
	rm -f /etc/ppp/sslvpnroute*
fi
rm -f /etc/ppp/sslvpn.clientip
rm -f /etc/ppp/peers/sslvpn.params.diag

# Reset ppp  user rights back to ubuntu default.
chmod -v 4754 /usr/sbin/pppd
chmod -v 766 /etc/ppp
chmod -v 2200 /etc/ppp/peers # right?

# Remove symlinks, they shouldn't be in use by any 
# in-distribution stuff anyway
rm /lib/libssl.so.6
rm /lib/libcrypto.so.6
